### ISSUE TITLE
Undefined index: session in SessionEngine:36

### ISSUE THREAD

**Issue by MjstcQueentin** [SmartNetApps/MajestiCloudAPI#1]
```
ErrorException: Undefined index: session in engine/session/SessionEngine.class.php:36
Stack trace:
#0 engine/session/SessionEngine.class.php(36): GlobalEngine->handle_error(8, 'Undefined index...', '...', 36, Array)
#1 public_endpoints/session/current.php(15): SessionEngine->logout()
#2 {main}
```

**Comment by MjstcQueentin** [comment]
Fixed with commit https://github.com/SmartNetApps/MajestiCloudAPI/commit/04d4a855f2d8e52d025f156d7d0cd4ecf634cc9f
